### ISSUE TITLE
ModuleNotFoundError: No module named 'vgg'

### ISSUE THREAD

**Issue by ydwang-good** [shaojiawei07/BottleNetPlusPlus#2]
Traceback (most recent call last):
  File "/WdHeDisk/users/wangyd/wangyd/24BottleNet/BottleNet++_VGG16.py", line 96, in <module>
    model = BottleNetPlusPlus_VGG().to(device)
  File "/WdHeDisk/users/wangyd/wangyd/24BottleNet/BottleNet++_VGG16.py", line 59, in __init__
    self.vgg_model = torch.load('vgg16_74.02.pth')
  File "/mnt/miniconda3/envs/wangyd/lib/python3.6/site-packages/torch/serialization.py", line 595, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/mnt/miniconda3/envs/wangyd/lib/python3.6/site-packages/torch/serialization.py", line 774, in _legacy_load
    result = unpickler.load()
ModuleNotFoundError: No module named 'vgg'

**Comment by marina-neseem** [comment]
same issue

**Comment by ydwang-good** [comment]
> same issue
it needs to train vgg to get new .pth  ourselves
